-- MySQL Script generated by MySQL Workbench
-- 05/29/15 11:23:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_pousada_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pousada_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pousada_system` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_pousada_system` ;

-- -----------------------------------------------------
-- Table `db_pousada_system`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pousada_system`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `db_pousada_system`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `privilegio` INT NOT NULL,
  `endereco` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idPessoa`, `login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pousada_system`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pousada_system`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `db_pousada_system`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Pessoa_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Cliente_Pessoa`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `db_pousada_system`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pousada_system`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pousada_system`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `db_pousada_system`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  INDEX `fk_Administrador_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Administrador_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `db_pousada_system`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pousada_system`.`Proprietario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pousada_system`.`Proprietario` ;

CREATE TABLE IF NOT EXISTS `db_pousada_system`.`Proprietario` (
  `idProprietario` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idProprietario`),
  INDEX `fk_Proprietario_Pessoa1_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Proprietario_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `db_pousada_system`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pousada_system`.`Chale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pousada_system`.`Chale` ;

CREATE TABLE IF NOT EXISTS `db_pousada_system`.`Chale` (
  `idChale` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `diaria` DOUBLE NOT NULL,
  PRIMARY KEY (`idChale`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pousada_system`.`Hospedagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pousada_system`.`Hospedagem` ;

CREATE TABLE IF NOT EXISTS `db_pousada_system`.`Hospedagem` (
  `idHospedagem` INT NOT NULL AUTO_INCREMENT,
  `quantAcomp` INT NOT NULL,
  `dataInicio` DATE NOT NULL,
  `previsao` INT NOT NULL,
  `dataSaida` DATE NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Chale_idChale` INT NOT NULL,
  PRIMARY KEY (`idHospedagem`),
  INDEX `fk_Hospedagem_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Hospedagem_Chale1_idx` (`Chale_idChale` ASC),
  CONSTRAINT `fk_Hospedagem_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `db_pousada_system`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospedagem_Chale1`
    FOREIGN KEY (`Chale_idChale`)
    REFERENCES `db_pousada_system`.`Chale` (`idChale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pousada_system`.`Equipamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pousada_system`.`Equipamento` ;

CREATE TABLE IF NOT EXISTS `db_pousada_system`.`Equipamento` (
  `idEquipamento` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idEquipamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pousada_system`.`ChaleEquipamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pousada_system`.`ChaleEquipamento` ;

CREATE TABLE IF NOT EXISTS `db_pousada_system`.`ChaleEquipamento` (
  `Chale_idChale` INT NOT NULL,
  `Equipamento_idEquipamento` INT NOT NULL,
  INDEX `fk_ChaleEquipamento_Chale1_idx` (`Chale_idChale` ASC),
  INDEX `fk_ChaleEquipamento_Equipamento1_idx` (`Equipamento_idEquipamento` ASC),
  CONSTRAINT `fk_ChaleEquipamento_Chale1`
    FOREIGN KEY (`Chale_idChale`)
    REFERENCES `db_pousada_system`.`Chale` (`idChale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChaleEquipamento_Equipamento1`
    FOREIGN KEY (`Equipamento_idEquipamento`)
    REFERENCES `db_pousada_system`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pousada_system`.`Reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pousada_system`.`Reserva` ;

CREATE TABLE IF NOT EXISTS `db_pousada_system`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `dataInicio` DATE NOT NULL,
  `dataFim` DATE NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Chale_idChale` INT NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reserva_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Reserva_Chale1_idx` (`Chale_idChale` ASC),
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `db_pousada_system`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Chale1`
    FOREIGN KEY (`Chale_idChale`)
    REFERENCES `db_pousada_system`.`Chale` (`idChale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
